#!/bin/bash

# shellcheck source=/dev/null
. "$(dirname "$0")/config"

perform_check() {
	prog="${prog#*/}"
	local flag="$FLAGS_DIR/${prog%.*}"
	local ret

	check
	ret=$?
	if [ $ret = 1 ]; then
	  fix
	  check
	  ret=$?
	  [ $ret = 0 ] && tg_say.sh "Возникла ошибка: $error_msg. Но проблема была автоматически исправлена." && return 0
	fi

	if [ $ret = 1 -a ! -f "$flag" ]; then
        	tg_say.sh "$error_msg" && touch "$flag"
	elif [ $ret = 0 -a -f "$flag" ]; then
        	rm "$flag" && tg_say.sh "$info_msg"

	fi
	return 0
}

check() {
  return 0
}

fix() {
  return 0
}

prog="$1"
[ -z "$prog" ] && exit 1
error_msg="$prog: fail"
info_msg="$prog: ok"

mkdir -p "$FLAGS_DIR"

. "$WORKDIR/$prog"
perform_check

exit 0
