#!/bin/bash

# shellcheck source=/dev/null
. "$(dirname "$0")/config"

perform_check() {
  local prog="${1#*/}"
  prog="${prog%.*}"
  local flag="$FLAGS_DIR/$prog"
  local log="$LOG_DIR/$prog.log"
  local ret

  echo "$(date "+%Y-%m-%d %H:%M:%S"): START $prog" >> "$log"
  set -x
  { check 2>&1; } >> "$log"
  ret=$?
  if [ $ret = 1 ]; then
    { fix 2>&1; }>> "$log"
    { check 2>&1; }>> "$log"
    ret=$?
    [ $ret = 0 ] && tg_say.sh "Возникла ошибка: $error_msg. Но проблема была автоматически исправлена." && return 0
  fi
  set +x

  if [ $ret = 1 -a ! -f "$flag" ]; then
          tg_say.sh "$error_msg" && touch "$flag"
  elif [ $ret = 0 -a -f "$flag" ]; then
          rm "$flag" && tg_say.sh "$info_msg"
  fi
  echo -e "$(date "+%Y-%m-%d %H:%M:%S"): END $prog\n" >> "$log"

  return 0
}

check() {
  return 0
}

fix() {
  return 0
}

prog="$1"
[ -z "$prog" ] && exit 1
error_msg="$prog: fail"
info_msg="$prog: ok"

mkdir -p "$FLAGS_DIR"
mkdir -p "$LOG_DIR"

. "$WORKDIR/$prog"
perform_check "$prog"

exit 0
